[package]
name = "wwama"
version = "0.1.0"
edition = "2024"
description = "Rust wrapper crate for llama.cpp with native, wasm32, and wasm64 builds."
readme = "README.md"
license = "Apache-2.0"
build = "build.rs"
links = "llama"

[dependencies]
libm = "0.2"

[build-dependencies]
cmake = "0.1.58"

[features]
default = ["webgpu"]
std = []
webgpu = []
